CREATE TABLE `tb_user_etc` (
  `USER_ID` varchar(20) NOT NULL COMMENT '관리자ID',
  `ETC_INFO1` varchar(50) DEFAULT NULL COMMENT 'ETC_INFO1',
  `ETC_INFO2` varchar(50) DEFAULT NULL COMMENT 'ETC_INFO2',
  `ETC_INFO3` varchar(50) DEFAULT NULL COMMENT 'ETC_INFO3',
  `ETC_INFO4` varchar(50) DEFAULT NULL COMMENT 'ETC_INFO4',
  `ETC_INFO5` varchar(50) DEFAULT NULL COMMENT 'ETC_INFO5',
  `REG_DTTM` timestamp NULL DEFAULT current_timestamp() COMMENT '등록일자',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB  COMMENT='사용자 기타'